/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as SejaAfiliadoRouteImport } from './routes/seja-afiliado'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RastrearPedidoRouteImport } from './routes/rastrear-pedido'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaContaIndexRouteImport } from './routes/minha-conta/index'
import { Route as BeneficioIndexRouteImport } from './routes/beneficio/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'
import { Route as AfiliadoRecuperarSenhaRouteImport } from './routes/afiliado/recuperar-senha'
import { Route as AfiliadoLoginRouteImport } from './routes/afiliado/login'
import { Route as AfiliadoDashboardRouteImport } from './routes/afiliado/dashboard'
import { Route as AfiliadoCadastroSucessoRouteImport } from './routes/afiliado/cadastro-sucesso'
import { Route as AfiliadoCadastroRouteImport } from './routes/afiliado/cadastro'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminSacRouteImport } from './routes/admin/sac'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReembolsosRouteImport } from './routes/admin/reembolsos'
import { Route as AdminRedesSociaisRouteImport } from './routes/admin/redes-sociais'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminPagamentosRouteImport } from './routes/admin/pagamentos'
import { Route as AdminNotificacoesRouteImport } from './routes/admin/notificacoes'
import { Route as AdminNfeRouteImport } from './routes/admin/nfe'
import { Route as AdminLoyaltyRouteImport } from './routes/admin/loyalty'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminLogisticaRouteImport } from './routes/admin/logistica'
import { Route as AdminIntegracoesRouteImport } from './routes/admin/integracoes'
import { Route as AdminFranRecomendaRouteImport } from './routes/admin/fran-recomenda'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminCuponsRouteImport } from './routes/admin/cupons'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminCampanhasRouteImport } from './routes/admin/campanhas'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAtendimentoIaRouteImport } from './routes/admin/atendimento-ia'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAlterarSenhaRouteImport } from './routes/admin/alterar-senha'
import { Route as AdminAfiliadosRouteImport } from './routes/admin/afiliados'
import { Route as MinhaContaPerfilIndexRouteImport } from './routes/minha-conta/perfil/index'
import { Route as MinhaContaPedidosIndexRouteImport } from './routes/minha-conta/pedidos/index'
import { Route as MinhaContaNotificacoesIndexRouteImport } from './routes/minha-conta/notificacoes/index'
import { Route as MinhaContaFavoritosIndexRouteImport } from './routes/minha-conta/favoritos/index'
import { Route as MinhaContaEnderecosIndexRouteImport } from './routes/minha-conta/enderecos/index'
import { Route as MinhaContaDevolucoesIndexRouteImport } from './routes/minha-conta/devolucoes/index'
import { Route as MinhaContaCancelamentosIndexRouteImport } from './routes/minha-conta/cancelamentos/index'
import { Route as MinhaContaAvaliacoesIndexRouteImport } from './routes/minha-conta/avaliacoes/index'
import { Route as AfiliadoDashboardIndexRouteImport } from './routes/afiliado/dashboard/index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as MinhaContaPedidosOrderIdRouteImport } from './routes/minha-conta/pedidos/$orderId'
import { Route as ApiPublicZernioWebhookRouteImport } from './routes/api/public/zernio-webhook'
import { Route as ApiPublicZernioStatusWebhookRouteImport } from './routes/api/public/zernio-status-webhook'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiPublicGoogleFeedRouteImport } from './routes/api/public/google-feed'
import { Route as ApiMarketingTrackRouteImport } from './routes/api/marketing/track'
import { Route as ApiMarketingSessionRouteImport } from './routes/api/marketing/session'
import { Route as ApiDebugFeaturedRouteImport } from './routes/api/debug/featured'
import { Route as ApiCronSincronizarRastreiosRouteImport } from './routes/api/cron/sincronizar-rastreios'
import { Route as ApiCronMarketingAutomationRouteImport } from './routes/api/cron/marketing-automation'
import { Route as ApiAdminEtiquetaZplRouteImport } from './routes/api/admin/etiqueta-zpl'
import { Route as ApiAdminEtiquetaRouteImport } from './routes/api/admin/etiqueta'
import { Route as AfiliadoDashboardVendasRouteImport } from './routes/afiliado/dashboard/vendas'
import { Route as AfiliadoDashboardPagamentosRouteImport } from './routes/afiliado/dashboard/pagamentos'
import { Route as AfiliadoDashboardLinksRouteImport } from './routes/afiliado/dashboard/links'
import { Route as AfiliadoDashboardConfiguracoesRouteImport } from './routes/afiliado/dashboard/configuracoes'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos/novo'
import { Route as AdminProdutosImagensRouteImport } from './routes/admin/produtos/imagens'
import { Route as ApiMarketingSessionCustomerRouteImport } from './routes/api/marketing/session/customer'
import { Route as AdminProdutosIdEditarRouteImport } from './routes/admin/produtos/$id/editar'

const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaAfiliadoRoute = SejaAfiliadoRouteImport.update({
  id: '/seja-afiliado',
  path: '/seja-afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearPedidoRoute = RastrearPedidoRouteImport.update({
  id: '/rastrear-pedido',
  path: '/rastrear-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaIndexRoute = MinhaContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const BeneficioIndexRoute = BeneficioIndexRouteImport.update({
  id: '/beneficio/',
  path: '/beneficio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoRecuperarSenhaRoute = AfiliadoRecuperarSenhaRouteImport.update({
  id: '/afiliado/recuperar-senha',
  path: '/afiliado/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoLoginRoute = AfiliadoLoginRouteImport.update({
  id: '/afiliado/login',
  path: '/afiliado/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoDashboardRoute = AfiliadoDashboardRouteImport.update({
  id: '/afiliado/dashboard',
  path: '/afiliado/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoCadastroSucessoRoute = AfiliadoCadastroSucessoRouteImport.update({
  id: '/afiliado/cadastro-sucesso',
  path: '/afiliado/cadastro-sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoCadastroRoute = AfiliadoCadastroRouteImport.update({
  id: '/afiliado/cadastro',
  path: '/afiliado/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSacRoute = AdminSacRouteImport.update({
  id: '/sac',
  path: '/sac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReembolsosRoute = AdminReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedesSociaisRoute = AdminRedesSociaisRouteImport.update({
  id: '/redes-sociais',
  path: '/redes-sociais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacoesRoute = AdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfeRoute = AdminNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFranRecomendaRoute = AdminFranRecomendaRouteImport.update({
  id: '/fran-recomenda',
  path: '/fran-recomenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtendimentoIaRoute = AdminAtendimentoIaRouteImport.update({
  id: '/atendimento-ia',
  path: '/atendimento-ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlterarSenhaRoute = AdminAlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const MinhaContaPerfilIndexRoute = MinhaContaPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaPedidosIndexRoute = MinhaContaPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaNotificacoesIndexRoute =
  MinhaContaNotificacoesIndexRouteImport.update({
    id: '/notificacoes/',
    path: '/notificacoes/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaFavoritosIndexRoute =
  MinhaContaFavoritosIndexRouteImport.update({
    id: '/favoritos/',
    path: '/favoritos/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaEnderecosIndexRoute =
  MinhaContaEnderecosIndexRouteImport.update({
    id: '/enderecos/',
    path: '/enderecos/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaDevolucoesIndexRoute =
  MinhaContaDevolucoesIndexRouteImport.update({
    id: '/devolucoes/',
    path: '/devolucoes/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaCancelamentosIndexRoute =
  MinhaContaCancelamentosIndexRouteImport.update({
    id: '/cancelamentos/',
    path: '/cancelamentos/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaAvaliacoesIndexRoute =
  MinhaContaAvaliacoesIndexRouteImport.update({
    id: '/avaliacoes/',
    path: '/avaliacoes/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const AfiliadoDashboardIndexRoute = AfiliadoDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const MinhaContaPedidosOrderIdRoute =
  MinhaContaPedidosOrderIdRouteImport.update({
    id: '/pedidos/$orderId',
    path: '/pedidos/$orderId',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const ApiPublicZernioWebhookRoute = ApiPublicZernioWebhookRouteImport.update({
  id: '/api/public/zernio-webhook',
  path: '/api/public/zernio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZernioStatusWebhookRoute =
  ApiPublicZernioStatusWebhookRouteImport.update({
    id: '/api/public/zernio-status-webhook',
    path: '/api/public/zernio-status-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleFeedRoute = ApiPublicGoogleFeedRouteImport.update({
  id: '/api/public/google-feed',
  path: '/api/public/google-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingTrackRoute = ApiMarketingTrackRouteImport.update({
  id: '/api/marketing/track',
  path: '/api/marketing/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingSessionRoute = ApiMarketingSessionRouteImport.update({
  id: '/api/marketing/session',
  path: '/api/marketing/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugFeaturedRoute = ApiDebugFeaturedRouteImport.update({
  id: '/api/debug/featured',
  path: '/api/debug/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSincronizarRastreiosRoute =
  ApiCronSincronizarRastreiosRouteImport.update({
    id: '/api/cron/sincronizar-rastreios',
    path: '/api/cron/sincronizar-rastreios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronMarketingAutomationRoute =
  ApiCronMarketingAutomationRouteImport.update({
    id: '/api/cron/marketing-automation',
    path: '/api/cron/marketing-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminEtiquetaZplRoute = ApiAdminEtiquetaZplRouteImport.update({
  id: '/api/admin/etiqueta-zpl',
  path: '/api/admin/etiqueta-zpl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEtiquetaRoute = ApiAdminEtiquetaRouteImport.update({
  id: '/api/admin/etiqueta',
  path: '/api/admin/etiqueta',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoDashboardVendasRoute = AfiliadoDashboardVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const AfiliadoDashboardPagamentosRoute =
  AfiliadoDashboardPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AfiliadoDashboardRoute,
  } as any)
const AfiliadoDashboardLinksRoute = AfiliadoDashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const AfiliadoDashboardConfiguracoesRoute =
  AfiliadoDashboardConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AfiliadoDashboardRoute,
  } as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosImagensRoute = AdminProdutosImagensRouteImport.update({
  id: '/imagens',
  path: '/imagens',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const ApiMarketingSessionCustomerRoute =
  ApiMarketingSessionCustomerRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => ApiMarketingSessionRoute,
  } as any)
const AdminProdutosIdEditarRoute = AdminProdutosIdEditarRouteImport.update({
  id: '/$id/editar',
  path: '/$id/editar',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/simulador': typeof SimuladorRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alterar-senha': typeof AdminAlterarSenhaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fran-recomenda': typeof AdminFranRecomendaRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/nfe': typeof AdminNfeRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardRouteWithChildren
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/beneficio/': typeof BeneficioIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/produtos/imagens': typeof AdminProdutosImagensRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/admin/etiqueta': typeof ApiAdminEtiquetaRoute
  '/api/admin/etiqueta-zpl': typeof ApiAdminEtiquetaZplRoute
  '/api/cron/marketing-automation': typeof ApiCronMarketingAutomationRoute
  '/api/cron/sincronizar-rastreios': typeof ApiCronSincronizarRastreiosRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/marketing/session': typeof ApiMarketingSessionRouteWithChildren
  '/api/marketing/track': typeof ApiMarketingTrackRoute
  '/api/public/google-feed': typeof ApiPublicGoogleFeedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/zernio-status-webhook': typeof ApiPublicZernioStatusWebhookRoute
  '/api/public/zernio-webhook': typeof ApiPublicZernioWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/afiliado/dashboard/': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/avaliacoes/': typeof MinhaContaAvaliacoesIndexRoute
  '/minha-conta/cancelamentos/': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/devolucoes/': typeof MinhaContaDevolucoesIndexRoute
  '/minha-conta/enderecos/': typeof MinhaContaEnderecosIndexRoute
  '/minha-conta/favoritos/': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes/': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/pedidos/': typeof MinhaContaPedidosIndexRoute
  '/minha-conta/perfil/': typeof MinhaContaPerfilIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/marketing/session/customer': typeof ApiMarketingSessionCustomerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/simulador': typeof SimuladorRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alterar-senha': typeof AdminAlterarSenhaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fran-recomenda': typeof AdminFranRecomendaRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/nfe': typeof AdminNfeRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
  '/beneficio': typeof BeneficioIndexRoute
  '/minha-conta': typeof MinhaContaIndexRoute
  '/admin/produtos/imagens': typeof AdminProdutosImagensRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/admin/etiqueta': typeof ApiAdminEtiquetaRoute
  '/api/admin/etiqueta-zpl': typeof ApiAdminEtiquetaZplRoute
  '/api/cron/marketing-automation': typeof ApiCronMarketingAutomationRoute
  '/api/cron/sincronizar-rastreios': typeof ApiCronSincronizarRastreiosRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/marketing/session': typeof ApiMarketingSessionRouteWithChildren
  '/api/marketing/track': typeof ApiMarketingTrackRoute
  '/api/public/google-feed': typeof ApiPublicGoogleFeedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/zernio-status-webhook': typeof ApiPublicZernioStatusWebhookRoute
  '/api/public/zernio-webhook': typeof ApiPublicZernioWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/avaliacoes': typeof MinhaContaAvaliacoesIndexRoute
  '/minha-conta/cancelamentos': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/devolucoes': typeof MinhaContaDevolucoesIndexRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosIndexRoute
  '/minha-conta/favoritos': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosIndexRoute
  '/minha-conta/perfil': typeof MinhaContaPerfilIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/marketing/session/customer': typeof ApiMarketingSessionCustomerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/simulador': typeof SimuladorRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/alterar-senha': typeof AdminAlterarSenhaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/fran-recomenda': typeof AdminFranRecomendaRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/nfe': typeof AdminNfeRoute
  '/admin/notificacoes': typeof AdminNotificacoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reembolsos': typeof AdminReembolsosRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardRouteWithChildren
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/beneficio/': typeof BeneficioIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/produtos/imagens': typeof AdminProdutosImagensRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/admin/etiqueta': typeof ApiAdminEtiquetaRoute
  '/api/admin/etiqueta-zpl': typeof ApiAdminEtiquetaZplRoute
  '/api/cron/marketing-automation': typeof ApiCronMarketingAutomationRoute
  '/api/cron/sincronizar-rastreios': typeof ApiCronSincronizarRastreiosRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/marketing/session': typeof ApiMarketingSessionRouteWithChildren
  '/api/marketing/track': typeof ApiMarketingTrackRoute
  '/api/public/google-feed': typeof ApiPublicGoogleFeedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/zernio-status-webhook': typeof ApiPublicZernioStatusWebhookRoute
  '/api/public/zernio-webhook': typeof ApiPublicZernioWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/afiliado/dashboard/': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/avaliacoes/': typeof MinhaContaAvaliacoesIndexRoute
  '/minha-conta/cancelamentos/': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/devolucoes/': typeof MinhaContaDevolucoesIndexRoute
  '/minha-conta/enderecos/': typeof MinhaContaEnderecosIndexRoute
  '/minha-conta/favoritos/': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes/': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/pedidos/': typeof MinhaContaPedidosIndexRoute
  '/minha-conta/perfil/': typeof MinhaContaPerfilIndexRoute
  '/admin/produtos/$id/editar': typeof AdminProdutosIdEditarRoute
  '/api/marketing/session/customer': typeof ApiMarketingSessionCustomerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-afiliado'
    | '/simulador'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/alterar-senha'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/financeiro'
    | '/admin/fran-recomenda'
    | '/admin/integracoes'
    | '/admin/logistica'
    | '/admin/logs'
    | '/admin/loyalty'
    | '/admin/nfe'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/redes-sociais'
    | '/admin/reembolsos'
    | '/admin/reviews'
    | '/admin/sac'
    | '/admin/usuarios'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/dashboard'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/pedido/$token'
    | '/produto/$id'
    | '/admin/'
    | '/beneficio/'
    | '/minha-conta/'
    | '/admin/produtos/imagens'
    | '/admin/produtos/novo'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/admin/etiqueta'
    | '/api/admin/etiqueta-zpl'
    | '/api/cron/marketing-automation'
    | '/api/cron/sincronizar-rastreios'
    | '/api/debug/featured'
    | '/api/marketing/session'
    | '/api/marketing/track'
    | '/api/public/google-feed'
    | '/api/public/mp-webhook'
    | '/api/public/zernio-status-webhook'
    | '/api/public/zernio-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/admin/produtos/'
    | '/afiliado/dashboard/'
    | '/minha-conta/avaliacoes/'
    | '/minha-conta/cancelamentos/'
    | '/minha-conta/devolucoes/'
    | '/minha-conta/enderecos/'
    | '/minha-conta/favoritos/'
    | '/minha-conta/notificacoes/'
    | '/minha-conta/pedidos/'
    | '/minha-conta/perfil/'
    | '/admin/produtos/$id/editar'
    | '/api/marketing/session/customer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-afiliado'
    | '/simulador'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/alterar-senha'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/financeiro'
    | '/admin/fran-recomenda'
    | '/admin/integracoes'
    | '/admin/logistica'
    | '/admin/logs'
    | '/admin/loyalty'
    | '/admin/nfe'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/redes-sociais'
    | '/admin/reembolsos'
    | '/admin/reviews'
    | '/admin/sac'
    | '/admin/usuarios'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/pedido/$token'
    | '/produto/$id'
    | '/admin'
    | '/beneficio'
    | '/minha-conta'
    | '/admin/produtos/imagens'
    | '/admin/produtos/novo'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/admin/etiqueta'
    | '/api/admin/etiqueta-zpl'
    | '/api/cron/marketing-automation'
    | '/api/cron/sincronizar-rastreios'
    | '/api/debug/featured'
    | '/api/marketing/session'
    | '/api/marketing/track'
    | '/api/public/google-feed'
    | '/api/public/mp-webhook'
    | '/api/public/zernio-status-webhook'
    | '/api/public/zernio-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/admin/produtos'
    | '/afiliado/dashboard'
    | '/minha-conta/avaliacoes'
    | '/minha-conta/cancelamentos'
    | '/minha-conta/devolucoes'
    | '/minha-conta/enderecos'
    | '/minha-conta/favoritos'
    | '/minha-conta/notificacoes'
    | '/minha-conta/pedidos'
    | '/minha-conta/perfil'
    | '/admin/produtos/$id/editar'
    | '/api/marketing/session/customer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/seja-afiliado'
    | '/simulador'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/alterar-senha'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/banners'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/financeiro'
    | '/admin/fran-recomenda'
    | '/admin/integracoes'
    | '/admin/logistica'
    | '/admin/logs'
    | '/admin/loyalty'
    | '/admin/nfe'
    | '/admin/notificacoes'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/redes-sociais'
    | '/admin/reembolsos'
    | '/admin/reviews'
    | '/admin/sac'
    | '/admin/usuarios'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/dashboard'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/pedido/$token'
    | '/produto/$id'
    | '/admin/'
    | '/beneficio/'
    | '/minha-conta/'
    | '/admin/produtos/imagens'
    | '/admin/produtos/novo'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/admin/etiqueta'
    | '/api/admin/etiqueta-zpl'
    | '/api/cron/marketing-automation'
    | '/api/cron/sincronizar-rastreios'
    | '/api/debug/featured'
    | '/api/marketing/session'
    | '/api/marketing/track'
    | '/api/public/google-feed'
    | '/api/public/mp-webhook'
    | '/api/public/zernio-status-webhook'
    | '/api/public/zernio-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/admin/produtos/'
    | '/afiliado/dashboard/'
    | '/minha-conta/avaliacoes/'
    | '/minha-conta/cancelamentos/'
    | '/minha-conta/devolucoes/'
    | '/minha-conta/enderecos/'
    | '/minha-conta/favoritos/'
    | '/minha-conta/notificacoes/'
    | '/minha-conta/pedidos/'
    | '/minha-conta/perfil/'
    | '/admin/produtos/$id/editar'
    | '/api/marketing/session/customer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  CompararRoute: typeof CompararRoute
  ContatoRoute: typeof ContatoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  RastrearPedidoRoute: typeof RastrearPedidoRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SejaAfiliadoRoute: typeof SejaAfiliadoRoute
  SimuladorRoute: typeof SimuladorRoute
  TermosRoute: typeof TermosRoute
  TrocasRoute: typeof TrocasRoute
  AfiliadoCadastroRoute: typeof AfiliadoCadastroRoute
  AfiliadoCadastroSucessoRoute: typeof AfiliadoCadastroSucessoRoute
  AfiliadoDashboardRoute: typeof AfiliadoDashboardRouteWithChildren
  AfiliadoLoginRoute: typeof AfiliadoLoginRoute
  AfiliadoRecuperarSenhaRoute: typeof AfiliadoRecuperarSenhaRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  BeneficioIndexRoute: typeof BeneficioIndexRoute
  ApiAdminEtiquetaRoute: typeof ApiAdminEtiquetaRoute
  ApiAdminEtiquetaZplRoute: typeof ApiAdminEtiquetaZplRoute
  ApiCronMarketingAutomationRoute: typeof ApiCronMarketingAutomationRoute
  ApiCronSincronizarRastreiosRoute: typeof ApiCronSincronizarRastreiosRoute
  ApiDebugFeaturedRoute: typeof ApiDebugFeaturedRoute
  ApiMarketingSessionRoute: typeof ApiMarketingSessionRouteWithChildren
  ApiMarketingTrackRoute: typeof ApiMarketingTrackRoute
  ApiPublicGoogleFeedRoute: typeof ApiPublicGoogleFeedRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicZernioStatusWebhookRoute: typeof ApiPublicZernioStatusWebhookRoute
  ApiPublicZernioWebhookRoute: typeof ApiPublicZernioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-afiliado': {
      id: '/seja-afiliado'
      path: '/seja-afiliado'
      fullPath: '/seja-afiliado'
      preLoaderRoute: typeof SejaAfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear-pedido': {
      id: '/rastrear-pedido'
      path: '/rastrear-pedido'
      fullPath: '/rastrear-pedido'
      preLoaderRoute: typeof RastrearPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/': {
      id: '/minha-conta/'
      path: '/'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof MinhaContaIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/beneficio/': {
      id: '/beneficio/'
      path: '/beneficio'
      fullPath: '/beneficio/'
      preLoaderRoute: typeof BeneficioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/recuperar-senha': {
      id: '/afiliado/recuperar-senha'
      path: '/afiliado/recuperar-senha'
      fullPath: '/afiliado/recuperar-senha'
      preLoaderRoute: typeof AfiliadoRecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/login': {
      id: '/afiliado/login'
      path: '/afiliado/login'
      fullPath: '/afiliado/login'
      preLoaderRoute: typeof AfiliadoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/dashboard': {
      id: '/afiliado/dashboard'
      path: '/afiliado/dashboard'
      fullPath: '/afiliado/dashboard'
      preLoaderRoute: typeof AfiliadoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/cadastro-sucesso': {
      id: '/afiliado/cadastro-sucesso'
      path: '/afiliado/cadastro-sucesso'
      fullPath: '/afiliado/cadastro-sucesso'
      preLoaderRoute: typeof AfiliadoCadastroSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/cadastro': {
      id: '/afiliado/cadastro'
      path: '/afiliado/cadastro'
      fullPath: '/afiliado/cadastro'
      preLoaderRoute: typeof AfiliadoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sac': {
      id: '/admin/sac'
      path: '/sac'
      fullPath: '/admin/sac'
      preLoaderRoute: typeof AdminSacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reembolsos': {
      id: '/admin/reembolsos'
      path: '/reembolsos'
      fullPath: '/admin/reembolsos'
      preLoaderRoute: typeof AdminReembolsosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redes-sociais': {
      id: '/admin/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/admin/redes-sociais'
      preLoaderRoute: typeof AdminRedesSociaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificacoes': {
      id: '/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/admin/notificacoes'
      preLoaderRoute: typeof AdminNotificacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfe': {
      id: '/admin/nfe'
      path: '/nfe'
      fullPath: '/admin/nfe'
      preLoaderRoute: typeof AdminNfeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fran-recomenda': {
      id: '/admin/fran-recomenda'
      path: '/fran-recomenda'
      fullPath: '/admin/fran-recomenda'
      preLoaderRoute: typeof AdminFranRecomendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atendimento-ia': {
      id: '/admin/atendimento-ia'
      path: '/atendimento-ia'
      fullPath: '/admin/atendimento-ia'
      preLoaderRoute: typeof AdminAtendimentoIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alterar-senha': {
      id: '/admin/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/admin/alterar-senha'
      preLoaderRoute: typeof AdminAlterarSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/minha-conta/perfil/': {
      id: '/minha-conta/perfil/'
      path: '/perfil'
      fullPath: '/minha-conta/perfil/'
      preLoaderRoute: typeof MinhaContaPerfilIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/pedidos/': {
      id: '/minha-conta/pedidos/'
      path: '/pedidos'
      fullPath: '/minha-conta/pedidos/'
      preLoaderRoute: typeof MinhaContaPedidosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/notificacoes/': {
      id: '/minha-conta/notificacoes/'
      path: '/notificacoes'
      fullPath: '/minha-conta/notificacoes/'
      preLoaderRoute: typeof MinhaContaNotificacoesIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/favoritos/': {
      id: '/minha-conta/favoritos/'
      path: '/favoritos'
      fullPath: '/minha-conta/favoritos/'
      preLoaderRoute: typeof MinhaContaFavoritosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/enderecos/': {
      id: '/minha-conta/enderecos/'
      path: '/enderecos'
      fullPath: '/minha-conta/enderecos/'
      preLoaderRoute: typeof MinhaContaEnderecosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/devolucoes/': {
      id: '/minha-conta/devolucoes/'
      path: '/devolucoes'
      fullPath: '/minha-conta/devolucoes/'
      preLoaderRoute: typeof MinhaContaDevolucoesIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/cancelamentos/': {
      id: '/minha-conta/cancelamentos/'
      path: '/cancelamentos'
      fullPath: '/minha-conta/cancelamentos/'
      preLoaderRoute: typeof MinhaContaCancelamentosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/avaliacoes/': {
      id: '/minha-conta/avaliacoes/'
      path: '/avaliacoes'
      fullPath: '/minha-conta/avaliacoes/'
      preLoaderRoute: typeof MinhaContaAvaliacoesIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/afiliado/dashboard/': {
      id: '/afiliado/dashboard/'
      path: '/'
      fullPath: '/afiliado/dashboard/'
      preLoaderRoute: typeof AfiliadoDashboardIndexRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/minha-conta/pedidos/$orderId': {
      id: '/minha-conta/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/minha-conta/pedidos/$orderId'
      preLoaderRoute: typeof MinhaContaPedidosOrderIdRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/api/public/zernio-webhook': {
      id: '/api/public/zernio-webhook'
      path: '/api/public/zernio-webhook'
      fullPath: '/api/public/zernio-webhook'
      preLoaderRoute: typeof ApiPublicZernioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zernio-status-webhook': {
      id: '/api/public/zernio-status-webhook'
      path: '/api/public/zernio-status-webhook'
      fullPath: '/api/public/zernio-status-webhook'
      preLoaderRoute: typeof ApiPublicZernioStatusWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-feed': {
      id: '/api/public/google-feed'
      path: '/api/public/google-feed'
      fullPath: '/api/public/google-feed'
      preLoaderRoute: typeof ApiPublicGoogleFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/track': {
      id: '/api/marketing/track'
      path: '/api/marketing/track'
      fullPath: '/api/marketing/track'
      preLoaderRoute: typeof ApiMarketingTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing/session': {
      id: '/api/marketing/session'
      path: '/api/marketing/session'
      fullPath: '/api/marketing/session'
      preLoaderRoute: typeof ApiMarketingSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/featured': {
      id: '/api/debug/featured'
      path: '/api/debug/featured'
      fullPath: '/api/debug/featured'
      preLoaderRoute: typeof ApiDebugFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sincronizar-rastreios': {
      id: '/api/cron/sincronizar-rastreios'
      path: '/api/cron/sincronizar-rastreios'
      fullPath: '/api/cron/sincronizar-rastreios'
      preLoaderRoute: typeof ApiCronSincronizarRastreiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/marketing-automation': {
      id: '/api/cron/marketing-automation'
      path: '/api/cron/marketing-automation'
      fullPath: '/api/cron/marketing-automation'
      preLoaderRoute: typeof ApiCronMarketingAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/etiqueta-zpl': {
      id: '/api/admin/etiqueta-zpl'
      path: '/api/admin/etiqueta-zpl'
      fullPath: '/api/admin/etiqueta-zpl'
      preLoaderRoute: typeof ApiAdminEtiquetaZplRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/etiqueta': {
      id: '/api/admin/etiqueta'
      path: '/api/admin/etiqueta'
      fullPath: '/api/admin/etiqueta'
      preLoaderRoute: typeof ApiAdminEtiquetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/dashboard/vendas': {
      id: '/afiliado/dashboard/vendas'
      path: '/vendas'
      fullPath: '/afiliado/dashboard/vendas'
      preLoaderRoute: typeof AfiliadoDashboardVendasRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/pagamentos': {
      id: '/afiliado/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/afiliado/dashboard/pagamentos'
      preLoaderRoute: typeof AfiliadoDashboardPagamentosRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/links': {
      id: '/afiliado/dashboard/links'
      path: '/links'
      fullPath: '/afiliado/dashboard/links'
      preLoaderRoute: typeof AfiliadoDashboardLinksRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/configuracoes': {
      id: '/afiliado/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/afiliado/dashboard/configuracoes'
      preLoaderRoute: typeof AfiliadoDashboardConfiguracoesRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/imagens': {
      id: '/admin/produtos/imagens'
      path: '/imagens'
      fullPath: '/admin/produtos/imagens'
      preLoaderRoute: typeof AdminProdutosImagensRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/api/marketing/session/customer': {
      id: '/api/marketing/session/customer'
      path: '/customer'
      fullPath: '/api/marketing/session/customer'
      preLoaderRoute: typeof ApiMarketingSessionCustomerRouteImport
      parentRoute: typeof ApiMarketingSessionRoute
    }
    '/admin/produtos/$id/editar': {
      id: '/admin/produtos/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/produtos/$id/editar'
      preLoaderRoute: typeof AdminProdutosIdEditarRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosImagensRoute: typeof AdminProdutosImagensRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminProdutosIdEditarRoute: typeof AdminProdutosIdEditarRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosImagensRoute: AdminProdutosImagensRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminProdutosIdEditarRoute: AdminProdutosIdEditarRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminAlterarSenhaRoute: typeof AdminAlterarSenhaRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAtendimentoIaRoute: typeof AdminAtendimentoIaRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFranRecomendaRoute: typeof AdminFranRecomendaRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminNfeRoute: typeof AdminNfeRoute
  AdminNotificacoesRoute: typeof AdminNotificacoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminRedesSociaisRoute: typeof AdminRedesSociaisRoute
  AdminReembolsosRoute: typeof AdminReembolsosRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSacRoute: typeof AdminSacRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminAlterarSenhaRoute: AdminAlterarSenhaRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAtendimentoIaRoute: AdminAtendimentoIaRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFranRecomendaRoute: AdminFranRecomendaRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminNfeRoute: AdminNfeRoute,
  AdminNotificacoesRoute: AdminNotificacoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminRedesSociaisRoute: AdminRedesSociaisRoute,
  AdminReembolsosRoute: AdminReembolsosRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSacRoute: AdminSacRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaIndexRoute: typeof MinhaContaIndexRoute
  MinhaContaPedidosOrderIdRoute: typeof MinhaContaPedidosOrderIdRoute
  MinhaContaAvaliacoesIndexRoute: typeof MinhaContaAvaliacoesIndexRoute
  MinhaContaCancelamentosIndexRoute: typeof MinhaContaCancelamentosIndexRoute
  MinhaContaDevolucoesIndexRoute: typeof MinhaContaDevolucoesIndexRoute
  MinhaContaEnderecosIndexRoute: typeof MinhaContaEnderecosIndexRoute
  MinhaContaFavoritosIndexRoute: typeof MinhaContaFavoritosIndexRoute
  MinhaContaNotificacoesIndexRoute: typeof MinhaContaNotificacoesIndexRoute
  MinhaContaPedidosIndexRoute: typeof MinhaContaPedidosIndexRoute
  MinhaContaPerfilIndexRoute: typeof MinhaContaPerfilIndexRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaIndexRoute: MinhaContaIndexRoute,
  MinhaContaPedidosOrderIdRoute: MinhaContaPedidosOrderIdRoute,
  MinhaContaAvaliacoesIndexRoute: MinhaContaAvaliacoesIndexRoute,
  MinhaContaCancelamentosIndexRoute: MinhaContaCancelamentosIndexRoute,
  MinhaContaDevolucoesIndexRoute: MinhaContaDevolucoesIndexRoute,
  MinhaContaEnderecosIndexRoute: MinhaContaEnderecosIndexRoute,
  MinhaContaFavoritosIndexRoute: MinhaContaFavoritosIndexRoute,
  MinhaContaNotificacoesIndexRoute: MinhaContaNotificacoesIndexRoute,
  MinhaContaPedidosIndexRoute: MinhaContaPedidosIndexRoute,
  MinhaContaPerfilIndexRoute: MinhaContaPerfilIndexRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

interface AfiliadoDashboardRouteChildren {
  AfiliadoDashboardConfiguracoesRoute: typeof AfiliadoDashboardConfiguracoesRoute
  AfiliadoDashboardLinksRoute: typeof AfiliadoDashboardLinksRoute
  AfiliadoDashboardPagamentosRoute: typeof AfiliadoDashboardPagamentosRoute
  AfiliadoDashboardVendasRoute: typeof AfiliadoDashboardVendasRoute
  AfiliadoDashboardIndexRoute: typeof AfiliadoDashboardIndexRoute
}

const AfiliadoDashboardRouteChildren: AfiliadoDashboardRouteChildren = {
  AfiliadoDashboardConfiguracoesRoute: AfiliadoDashboardConfiguracoesRoute,
  AfiliadoDashboardLinksRoute: AfiliadoDashboardLinksRoute,
  AfiliadoDashboardPagamentosRoute: AfiliadoDashboardPagamentosRoute,
  AfiliadoDashboardVendasRoute: AfiliadoDashboardVendasRoute,
  AfiliadoDashboardIndexRoute: AfiliadoDashboardIndexRoute,
}

const AfiliadoDashboardRouteWithChildren =
  AfiliadoDashboardRoute._addFileChildren(AfiliadoDashboardRouteChildren)

interface ApiMarketingSessionRouteChildren {
  ApiMarketingSessionCustomerRoute: typeof ApiMarketingSessionCustomerRoute
}

const ApiMarketingSessionRouteChildren: ApiMarketingSessionRouteChildren = {
  ApiMarketingSessionCustomerRoute: ApiMarketingSessionCustomerRoute,
}

const ApiMarketingSessionRouteWithChildren =
  ApiMarketingSessionRoute._addFileChildren(ApiMarketingSessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  CompararRoute: CompararRoute,
  ContatoRoute: ContatoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  RastrearPedidoRoute: RastrearPedidoRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SejaAfiliadoRoute: SejaAfiliadoRoute,
  SimuladorRoute: SimuladorRoute,
  TermosRoute: TermosRoute,
  TrocasRoute: TrocasRoute,
  AfiliadoCadastroRoute: AfiliadoCadastroRoute,
  AfiliadoCadastroSucessoRoute: AfiliadoCadastroSucessoRoute,
  AfiliadoDashboardRoute: AfiliadoDashboardRouteWithChildren,
  AfiliadoLoginRoute: AfiliadoLoginRoute,
  AfiliadoRecuperarSenhaRoute: AfiliadoRecuperarSenhaRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  BeneficioIndexRoute: BeneficioIndexRoute,
  ApiAdminEtiquetaRoute: ApiAdminEtiquetaRoute,
  ApiAdminEtiquetaZplRoute: ApiAdminEtiquetaZplRoute,
  ApiCronMarketingAutomationRoute: ApiCronMarketingAutomationRoute,
  ApiCronSincronizarRastreiosRoute: ApiCronSincronizarRastreiosRoute,
  ApiDebugFeaturedRoute: ApiDebugFeaturedRoute,
  ApiMarketingSessionRoute: ApiMarketingSessionRouteWithChildren,
  ApiMarketingTrackRoute: ApiMarketingTrackRoute,
  ApiPublicGoogleFeedRoute: ApiPublicGoogleFeedRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicZernioStatusWebhookRoute: ApiPublicZernioStatusWebhookRoute,
  ApiPublicZernioWebhookRoute: ApiPublicZernioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
