/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SejaAfiliadoRouteImport } from './routes/seja-afiliado'
import { Route as RastrearPedidoRouteImport } from './routes/rastrear-pedido'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaContaIndexRouteImport } from './routes/minha-conta/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as MinhaContaPedidosRouteImport } from './routes/minha-conta/pedidos'
import { Route as AfiliadoRecuperarSenhaRouteImport } from './routes/afiliado/recuperar-senha'
import { Route as AfiliadoLoginRouteImport } from './routes/afiliado/login'
import { Route as AfiliadoDashboardRouteImport } from './routes/afiliado/dashboard'
import { Route as AfiliadoCadastroSucessoRouteImport } from './routes/afiliado/cadastro-sucesso'
import { Route as AfiliadoCadastroRouteImport } from './routes/afiliado/cadastro'
import { Route as AdminSacRouteImport } from './routes/admin/sac'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminRedesSociaisRouteImport } from './routes/admin/redes-sociais'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminPagamentosRouteImport } from './routes/admin/pagamentos'
import { Route as AdminLoyaltyRouteImport } from './routes/admin/loyalty'
import { Route as AdminLogisticaRouteImport } from './routes/admin/logistica'
import { Route as AdminCuponsRouteImport } from './routes/admin/cupons'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminAtendimentoIaRouteImport } from './routes/admin/atendimento-ia'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAfiliadosRouteImport } from './routes/admin/afiliados'
import { Route as MinhaContaPerfilIndexRouteImport } from './routes/minha-conta/perfil/index'
import { Route as MinhaContaNotificacoesIndexRouteImport } from './routes/minha-conta/notificacoes/index'
import { Route as MinhaContaFavoritosIndexRouteImport } from './routes/minha-conta/favoritos/index'
import { Route as MinhaContaCancelamentosIndexRouteImport } from './routes/minha-conta/cancelamentos/index'
import { Route as AfiliadoDashboardIndexRouteImport } from './routes/afiliado/dashboard/index'
import { Route as MinhaContaPedidosOrderIdRouteImport } from './routes/minha-conta/pedidos/$orderId'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as ApiDebugFeaturedRouteImport } from './routes/api/debug/featured'
import { Route as AfiliadoDashboardVendasRouteImport } from './routes/afiliado/dashboard/vendas'
import { Route as AfiliadoDashboardPagamentosRouteImport } from './routes/afiliado/dashboard/pagamentos'
import { Route as AfiliadoDashboardLinksRouteImport } from './routes/afiliado/dashboard/links'
import { Route as AfiliadoDashboardConfiguracoesRouteImport } from './routes/afiliado/dashboard/configuracoes'

const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaAfiliadoRoute = SejaAfiliadoRouteImport.update({
  id: '/seja-afiliado',
  path: '/seja-afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearPedidoRoute = RastrearPedidoRouteImport.update({
  id: '/rastrear-pedido',
  path: '/rastrear-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaIndexRoute = MinhaContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPedidosRoute = MinhaContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const AfiliadoRecuperarSenhaRoute = AfiliadoRecuperarSenhaRouteImport.update({
  id: '/afiliado/recuperar-senha',
  path: '/afiliado/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoLoginRoute = AfiliadoLoginRouteImport.update({
  id: '/afiliado/login',
  path: '/afiliado/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoDashboardRoute = AfiliadoDashboardRouteImport.update({
  id: '/afiliado/dashboard',
  path: '/afiliado/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoCadastroSucessoRoute = AfiliadoCadastroSucessoRouteImport.update({
  id: '/afiliado/cadastro-sucesso',
  path: '/afiliado/cadastro-sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoCadastroRoute = AfiliadoCadastroRouteImport.update({
  id: '/afiliado/cadastro',
  path: '/afiliado/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSacRoute = AdminSacRouteImport.update({
  id: '/sac',
  path: '/sac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedesSociaisRoute = AdminRedesSociaisRouteImport.update({
  id: '/redes-sociais',
  path: '/redes-sociais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoyaltyRoute = AdminLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtendimentoIaRoute = AdminAtendimentoIaRouteImport.update({
  id: '/atendimento-ia',
  path: '/atendimento-ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAfiliadosRoute = AdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AdminRoute,
} as any)
const MinhaContaPerfilIndexRoute = MinhaContaPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaNotificacoesIndexRoute =
  MinhaContaNotificacoesIndexRouteImport.update({
    id: '/notificacoes/',
    path: '/notificacoes/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaFavoritosIndexRoute =
  MinhaContaFavoritosIndexRouteImport.update({
    id: '/favoritos/',
    path: '/favoritos/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaCancelamentosIndexRoute =
  MinhaContaCancelamentosIndexRouteImport.update({
    id: '/cancelamentos/',
    path: '/cancelamentos/',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const AfiliadoDashboardIndexRoute = AfiliadoDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const MinhaContaPedidosOrderIdRoute =
  MinhaContaPedidosOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => MinhaContaPedidosRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugFeaturedRoute = ApiDebugFeaturedRouteImport.update({
  id: '/api/debug/featured',
  path: '/api/debug/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoDashboardVendasRoute = AfiliadoDashboardVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const AfiliadoDashboardPagamentosRoute =
  AfiliadoDashboardPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AfiliadoDashboardRoute,
  } as any)
const AfiliadoDashboardLinksRoute = AfiliadoDashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AfiliadoDashboardRoute,
} as any)
const AfiliadoDashboardConfiguracoesRoute =
  AfiliadoDashboardConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AfiliadoDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardRouteWithChildren
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/afiliado/dashboard/': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/cancelamentos/': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/favoritos/': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes/': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/perfil/': typeof MinhaContaPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin': typeof AdminIndexRoute
  '/minha-conta': typeof MinhaContaIndexRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/cancelamentos': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/favoritos': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/perfil': typeof MinhaContaPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/comparar': typeof CompararRoute
  '/contato': typeof ContatoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/rastrear-pedido': typeof RastrearPedidoRoute
  '/seja-afiliado': typeof SejaAfiliadoRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/admin/afiliados': typeof AdminAfiliadosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/atendimento-ia': typeof AdminAtendimentoIaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loyalty': typeof AdminLoyaltyRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/redes-sociais': typeof AdminRedesSociaisRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/sac': typeof AdminSacRoute
  '/afiliado/cadastro': typeof AfiliadoCadastroRoute
  '/afiliado/cadastro-sucesso': typeof AfiliadoCadastroSucessoRoute
  '/afiliado/dashboard': typeof AfiliadoDashboardRouteWithChildren
  '/afiliado/login': typeof AfiliadoLoginRoute
  '/afiliado/recuperar-senha': typeof AfiliadoRecuperarSenhaRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/afiliado/dashboard/configuracoes': typeof AfiliadoDashboardConfiguracoesRoute
  '/afiliado/dashboard/links': typeof AfiliadoDashboardLinksRoute
  '/afiliado/dashboard/pagamentos': typeof AfiliadoDashboardPagamentosRoute
  '/afiliado/dashboard/vendas': typeof AfiliadoDashboardVendasRoute
  '/api/debug/featured': typeof ApiDebugFeaturedRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/minha-conta/pedidos/$orderId': typeof MinhaContaPedidosOrderIdRoute
  '/afiliado/dashboard/': typeof AfiliadoDashboardIndexRoute
  '/minha-conta/cancelamentos/': typeof MinhaContaCancelamentosIndexRoute
  '/minha-conta/favoritos/': typeof MinhaContaFavoritosIndexRoute
  '/minha-conta/notificacoes/': typeof MinhaContaNotificacoesIndexRoute
  '/minha-conta/perfil/': typeof MinhaContaPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/seja-afiliado'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/logistica'
    | '/admin/loyalty'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/redes-sociais'
    | '/admin/reviews'
    | '/admin/sac'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/dashboard'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/minha-conta/'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/debug/featured'
    | '/api/public/mp-webhook'
    | '/api/public/whatsapp-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/afiliado/dashboard/'
    | '/minha-conta/cancelamentos/'
    | '/minha-conta/favoritos/'
    | '/minha-conta/notificacoes/'
    | '/minha-conta/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/seja-afiliado'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/logistica'
    | '/admin/loyalty'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/redes-sociais'
    | '/admin/reviews'
    | '/admin/sac'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin'
    | '/minha-conta'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/debug/featured'
    | '/api/public/mp-webhook'
    | '/api/public/whatsapp-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/afiliado/dashboard'
    | '/minha-conta/cancelamentos'
    | '/minha-conta/favoritos'
    | '/minha-conta/notificacoes'
    | '/minha-conta/perfil'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/comparar'
    | '/contato'
    | '/favoritos'
    | '/login'
    | '/minha-conta'
    | '/privacidade'
    | '/produtos'
    | '/rastrear-pedido'
    | '/seja-afiliado'
    | '/termos'
    | '/trocas'
    | '/admin/afiliados'
    | '/admin/analytics'
    | '/admin/atendimento-ia'
    | '/admin/configuracoes'
    | '/admin/crm'
    | '/admin/cupons'
    | '/admin/logistica'
    | '/admin/loyalty'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/redes-sociais'
    | '/admin/reviews'
    | '/admin/sac'
    | '/afiliado/cadastro'
    | '/afiliado/cadastro-sucesso'
    | '/afiliado/dashboard'
    | '/afiliado/login'
    | '/afiliado/recuperar-senha'
    | '/minha-conta/pedidos'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/'
    | '/minha-conta/'
    | '/afiliado/dashboard/configuracoes'
    | '/afiliado/dashboard/links'
    | '/afiliado/dashboard/pagamentos'
    | '/afiliado/dashboard/vendas'
    | '/api/debug/featured'
    | '/api/public/mp-webhook'
    | '/api/public/whatsapp-webhook'
    | '/minha-conta/pedidos/$orderId'
    | '/afiliado/dashboard/'
    | '/minha-conta/cancelamentos/'
    | '/minha-conta/favoritos/'
    | '/minha-conta/notificacoes/'
    | '/minha-conta/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  CompararRoute: typeof CompararRoute
  ContatoRoute: typeof ContatoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  RastrearPedidoRoute: typeof RastrearPedidoRoute
  SejaAfiliadoRoute: typeof SejaAfiliadoRoute
  TermosRoute: typeof TermosRoute
  TrocasRoute: typeof TrocasRoute
  AfiliadoCadastroRoute: typeof AfiliadoCadastroRoute
  AfiliadoCadastroSucessoRoute: typeof AfiliadoCadastroSucessoRoute
  AfiliadoDashboardRoute: typeof AfiliadoDashboardRouteWithChildren
  AfiliadoLoginRoute: typeof AfiliadoLoginRoute
  AfiliadoRecuperarSenhaRoute: typeof AfiliadoRecuperarSenhaRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiDebugFeaturedRoute: typeof ApiDebugFeaturedRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-afiliado': {
      id: '/seja-afiliado'
      path: '/seja-afiliado'
      fullPath: '/seja-afiliado'
      preLoaderRoute: typeof SejaAfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear-pedido': {
      id: '/rastrear-pedido'
      path: '/rastrear-pedido'
      fullPath: '/rastrear-pedido'
      preLoaderRoute: typeof RastrearPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/': {
      id: '/minha-conta/'
      path: '/'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof MinhaContaIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/pedidos': {
      id: '/minha-conta/pedidos'
      path: '/pedidos'
      fullPath: '/minha-conta/pedidos'
      preLoaderRoute: typeof MinhaContaPedidosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/afiliado/recuperar-senha': {
      id: '/afiliado/recuperar-senha'
      path: '/afiliado/recuperar-senha'
      fullPath: '/afiliado/recuperar-senha'
      preLoaderRoute: typeof AfiliadoRecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/login': {
      id: '/afiliado/login'
      path: '/afiliado/login'
      fullPath: '/afiliado/login'
      preLoaderRoute: typeof AfiliadoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/dashboard': {
      id: '/afiliado/dashboard'
      path: '/afiliado/dashboard'
      fullPath: '/afiliado/dashboard'
      preLoaderRoute: typeof AfiliadoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/cadastro-sucesso': {
      id: '/afiliado/cadastro-sucesso'
      path: '/afiliado/cadastro-sucesso'
      fullPath: '/afiliado/cadastro-sucesso'
      preLoaderRoute: typeof AfiliadoCadastroSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/cadastro': {
      id: '/afiliado/cadastro'
      path: '/afiliado/cadastro'
      fullPath: '/afiliado/cadastro'
      preLoaderRoute: typeof AfiliadoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sac': {
      id: '/admin/sac'
      path: '/sac'
      fullPath: '/admin/sac'
      preLoaderRoute: typeof AdminSacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redes-sociais': {
      id: '/admin/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/admin/redes-sociais'
      preLoaderRoute: typeof AdminRedesSociaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loyalty': {
      id: '/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AdminLoyaltyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atendimento-ia': {
      id: '/admin/atendimento-ia'
      path: '/atendimento-ia'
      fullPath: '/admin/atendimento-ia'
      preLoaderRoute: typeof AdminAtendimentoIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/afiliados': {
      id: '/admin/afiliados'
      path: '/afiliados'
      fullPath: '/admin/afiliados'
      preLoaderRoute: typeof AdminAfiliadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/minha-conta/perfil/': {
      id: '/minha-conta/perfil/'
      path: '/perfil'
      fullPath: '/minha-conta/perfil/'
      preLoaderRoute: typeof MinhaContaPerfilIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/notificacoes/': {
      id: '/minha-conta/notificacoes/'
      path: '/notificacoes'
      fullPath: '/minha-conta/notificacoes/'
      preLoaderRoute: typeof MinhaContaNotificacoesIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/favoritos/': {
      id: '/minha-conta/favoritos/'
      path: '/favoritos'
      fullPath: '/minha-conta/favoritos/'
      preLoaderRoute: typeof MinhaContaFavoritosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/cancelamentos/': {
      id: '/minha-conta/cancelamentos/'
      path: '/cancelamentos'
      fullPath: '/minha-conta/cancelamentos/'
      preLoaderRoute: typeof MinhaContaCancelamentosIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/afiliado/dashboard/': {
      id: '/afiliado/dashboard/'
      path: '/'
      fullPath: '/afiliado/dashboard/'
      preLoaderRoute: typeof AfiliadoDashboardIndexRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/minha-conta/pedidos/$orderId': {
      id: '/minha-conta/pedidos/$orderId'
      path: '/$orderId'
      fullPath: '/minha-conta/pedidos/$orderId'
      preLoaderRoute: typeof MinhaContaPedidosOrderIdRouteImport
      parentRoute: typeof MinhaContaPedidosRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/featured': {
      id: '/api/debug/featured'
      path: '/api/debug/featured'
      fullPath: '/api/debug/featured'
      preLoaderRoute: typeof ApiDebugFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado/dashboard/vendas': {
      id: '/afiliado/dashboard/vendas'
      path: '/vendas'
      fullPath: '/afiliado/dashboard/vendas'
      preLoaderRoute: typeof AfiliadoDashboardVendasRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/pagamentos': {
      id: '/afiliado/dashboard/pagamentos'
      path: '/pagamentos'
      fullPath: '/afiliado/dashboard/pagamentos'
      preLoaderRoute: typeof AfiliadoDashboardPagamentosRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/links': {
      id: '/afiliado/dashboard/links'
      path: '/links'
      fullPath: '/afiliado/dashboard/links'
      preLoaderRoute: typeof AfiliadoDashboardLinksRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
    '/afiliado/dashboard/configuracoes': {
      id: '/afiliado/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/afiliado/dashboard/configuracoes'
      preLoaderRoute: typeof AfiliadoDashboardConfiguracoesRouteImport
      parentRoute: typeof AfiliadoDashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAfiliadosRoute: typeof AdminAfiliadosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAtendimentoIaRoute: typeof AdminAtendimentoIaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminLoyaltyRoute: typeof AdminLoyaltyRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRedesSociaisRoute: typeof AdminRedesSociaisRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSacRoute: typeof AdminSacRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAfiliadosRoute: AdminAfiliadosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAtendimentoIaRoute: AdminAtendimentoIaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminLoyaltyRoute: AdminLoyaltyRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRedesSociaisRoute: AdminRedesSociaisRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSacRoute: AdminSacRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaPedidosRouteChildren {
  MinhaContaPedidosOrderIdRoute: typeof MinhaContaPedidosOrderIdRoute
}

const MinhaContaPedidosRouteChildren: MinhaContaPedidosRouteChildren = {
  MinhaContaPedidosOrderIdRoute: MinhaContaPedidosOrderIdRoute,
}

const MinhaContaPedidosRouteWithChildren =
  MinhaContaPedidosRoute._addFileChildren(MinhaContaPedidosRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaPedidosRoute: typeof MinhaContaPedidosRouteWithChildren
  MinhaContaIndexRoute: typeof MinhaContaIndexRoute
  MinhaContaCancelamentosIndexRoute: typeof MinhaContaCancelamentosIndexRoute
  MinhaContaFavoritosIndexRoute: typeof MinhaContaFavoritosIndexRoute
  MinhaContaNotificacoesIndexRoute: typeof MinhaContaNotificacoesIndexRoute
  MinhaContaPerfilIndexRoute: typeof MinhaContaPerfilIndexRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaPedidosRoute: MinhaContaPedidosRouteWithChildren,
  MinhaContaIndexRoute: MinhaContaIndexRoute,
  MinhaContaCancelamentosIndexRoute: MinhaContaCancelamentosIndexRoute,
  MinhaContaFavoritosIndexRoute: MinhaContaFavoritosIndexRoute,
  MinhaContaNotificacoesIndexRoute: MinhaContaNotificacoesIndexRoute,
  MinhaContaPerfilIndexRoute: MinhaContaPerfilIndexRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

interface AfiliadoDashboardRouteChildren {
  AfiliadoDashboardConfiguracoesRoute: typeof AfiliadoDashboardConfiguracoesRoute
  AfiliadoDashboardLinksRoute: typeof AfiliadoDashboardLinksRoute
  AfiliadoDashboardPagamentosRoute: typeof AfiliadoDashboardPagamentosRoute
  AfiliadoDashboardVendasRoute: typeof AfiliadoDashboardVendasRoute
  AfiliadoDashboardIndexRoute: typeof AfiliadoDashboardIndexRoute
}

const AfiliadoDashboardRouteChildren: AfiliadoDashboardRouteChildren = {
  AfiliadoDashboardConfiguracoesRoute: AfiliadoDashboardConfiguracoesRoute,
  AfiliadoDashboardLinksRoute: AfiliadoDashboardLinksRoute,
  AfiliadoDashboardPagamentosRoute: AfiliadoDashboardPagamentosRoute,
  AfiliadoDashboardVendasRoute: AfiliadoDashboardVendasRoute,
  AfiliadoDashboardIndexRoute: AfiliadoDashboardIndexRoute,
}

const AfiliadoDashboardRouteWithChildren =
  AfiliadoDashboardRoute._addFileChildren(AfiliadoDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  CompararRoute: CompararRoute,
  ContatoRoute: ContatoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  RastrearPedidoRoute: RastrearPedidoRoute,
  SejaAfiliadoRoute: SejaAfiliadoRoute,
  TermosRoute: TermosRoute,
  TrocasRoute: TrocasRoute,
  AfiliadoCadastroRoute: AfiliadoCadastroRoute,
  AfiliadoCadastroSucessoRoute: AfiliadoCadastroSucessoRoute,
  AfiliadoDashboardRoute: AfiliadoDashboardRouteWithChildren,
  AfiliadoLoginRoute: AfiliadoLoginRoute,
  AfiliadoRecuperarSenhaRoute: AfiliadoRecuperarSenhaRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiDebugFeaturedRoute: ApiDebugFeaturedRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
